springBootVersion=3.4.7



mybatisSpringBootStarter=3.0.3

## JDK_JAVA_OPTIONS
# --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED
org.gradle.jvmargs=-Xmx512m "-XX:MaxMetaspaceSize=384m"


