server:
  port: 8083
spring:
  application:
    name: SpringSecurityOAuth2-Google

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 75752582224-7ltvu93k1hs4b131uljmerokjqt74i0b.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    org.springframework.security.web.DefaultSecurityFilterChain: INFO

