// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: earthService.proto

package com.sample.grpc.protodefine;

public final class EarthServiceProto {
  private EarthServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EarthRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.testing.EarthRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    java.lang.String getRequestMessage();
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestMessageBytes();
  }
  /**
   * <pre>
   * A Earth request message type for test.
   * </pre>
   *
   * Protobuf type {@code grpc.testing.EarthRequest}
   */
  public  static final class EarthRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.testing.EarthRequest)
      EarthRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EarthRequest.newBuilder() to construct.
    private EarthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EarthRequest() {
      requestMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EarthRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EarthRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.class, com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.Builder.class);
    }

    public static final int REQUESTMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestMessage_;
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    public java.lang.String getRequestMessage() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMessageBytes() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sample.grpc.protodefine.EarthServiceProto.EarthRequest)) {
        return super.equals(obj);
      }
      com.sample.grpc.protodefine.EarthServiceProto.EarthRequest other = (com.sample.grpc.protodefine.EarthServiceProto.EarthRequest) obj;

      if (!getRequestMessage()
          .equals(other.getRequestMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sample.grpc.protodefine.EarthServiceProto.EarthRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A Earth request message type for test.
     * </pre>
     *
     * Protobuf type {@code grpc.testing.EarthRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.testing.EarthRequest)
        com.sample.grpc.protodefine.EarthServiceProto.EarthRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.class, com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.Builder.class);
      }

      // Construct using com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthRequest_descriptor;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthRequest getDefaultInstanceForType() {
        return com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthRequest build() {
        com.sample.grpc.protodefine.EarthServiceProto.EarthRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthRequest buildPartial() {
        com.sample.grpc.protodefine.EarthServiceProto.EarthRequest result = new com.sample.grpc.protodefine.EarthServiceProto.EarthRequest(this);
        result.requestMessage_ = requestMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sample.grpc.protodefine.EarthServiceProto.EarthRequest) {
          return mergeFrom((com.sample.grpc.protodefine.EarthServiceProto.EarthRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sample.grpc.protodefine.EarthServiceProto.EarthRequest other) {
        if (other == com.sample.grpc.protodefine.EarthServiceProto.EarthRequest.getDefaultInstance()) return this;
        if (!other.getRequestMessage().isEmpty()) {
          requestMessage_ = other.requestMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sample.grpc.protodefine.EarthServiceProto.EarthRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sample.grpc.protodefine.EarthServiceProto.EarthRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestMessage_ = "";
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public java.lang.String getRequestMessage() {
        java.lang.Object ref = requestMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMessageBytes() {
        java.lang.Object ref = requestMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder setRequestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder clearRequestMessage() {
        
        requestMessage_ = getDefaultInstance().getRequestMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder setRequestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.testing.EarthRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc.testing.EarthRequest)
    private static final com.sample.grpc.protodefine.EarthServiceProto.EarthRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sample.grpc.protodefine.EarthServiceProto.EarthRequest();
    }

    public static com.sample.grpc.protodefine.EarthServiceProto.EarthRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EarthRequest>
        PARSER = new com.google.protobuf.AbstractParser<EarthRequest>() {
      @java.lang.Override
      public EarthRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EarthRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EarthRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EarthRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sample.grpc.protodefine.EarthServiceProto.EarthRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EarthResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.testing.EarthResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * <pre>
   * A Earth response message type for test.
   * </pre>
   *
   * Protobuf type {@code grpc.testing.EarthResponse}
   */
  public  static final class EarthResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.testing.EarthResponse)
      EarthResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EarthResponse.newBuilder() to construct.
    private EarthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EarthResponse() {
      responseMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EarthResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EarthResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.class, com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sample.grpc.protodefine.EarthServiceProto.EarthResponse)) {
        return super.equals(obj);
      }
      com.sample.grpc.protodefine.EarthServiceProto.EarthResponse other = (com.sample.grpc.protodefine.EarthServiceProto.EarthResponse) obj;

      if (!getResponseMessage()
          .equals(other.getResponseMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sample.grpc.protodefine.EarthServiceProto.EarthResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A Earth response message type for test.
     * </pre>
     *
     * Protobuf type {@code grpc.testing.EarthResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.testing.EarthResponse)
        com.sample.grpc.protodefine.EarthServiceProto.EarthResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.class, com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.Builder.class);
      }

      // Construct using com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sample.grpc.protodefine.EarthServiceProto.internal_static_grpc_testing_EarthResponse_descriptor;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthResponse getDefaultInstanceForType() {
        return com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthResponse build() {
        com.sample.grpc.protodefine.EarthServiceProto.EarthResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.EarthServiceProto.EarthResponse buildPartial() {
        com.sample.grpc.protodefine.EarthServiceProto.EarthResponse result = new com.sample.grpc.protodefine.EarthServiceProto.EarthResponse(this);
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sample.grpc.protodefine.EarthServiceProto.EarthResponse) {
          return mergeFrom((com.sample.grpc.protodefine.EarthServiceProto.EarthResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sample.grpc.protodefine.EarthServiceProto.EarthResponse other) {
        if (other == com.sample.grpc.protodefine.EarthServiceProto.EarthResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sample.grpc.protodefine.EarthServiceProto.EarthResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sample.grpc.protodefine.EarthServiceProto.EarthResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.testing.EarthResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.testing.EarthResponse)
    private static final com.sample.grpc.protodefine.EarthServiceProto.EarthResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sample.grpc.protodefine.EarthServiceProto.EarthResponse();
    }

    public static com.sample.grpc.protodefine.EarthServiceProto.EarthResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EarthResponse>
        PARSER = new com.google.protobuf.AbstractParser<EarthResponse>() {
      @java.lang.Override
      public EarthResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EarthResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EarthResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EarthResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sample.grpc.protodefine.EarthServiceProto.EarthResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_EarthRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_EarthRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_EarthResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_EarthResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022earthService.proto\022\014grpc.testing\"&\n\014Ea" +
      "rthRequest\022\026\n\016requestMessage\030\001 \001(\t\"(\n\rEa" +
      "rthResponse\022\027\n\017responseMessage\030\001 \001(\t2\316\002\n" +
      "\014EarthService\022E\n\010UnaryRpc\022\032.grpc.testing" +
      ".EarthRequest\032\033.grpc.testing.EarthRespon" +
      "se\"\000\022Q\n\022ClientStreamingRpc\022\032.grpc.testin" +
      "g.EarthRequest\032\033.grpc.testing.EarthRespo" +
      "nse\"\000(\001\022Q\n\022ServerStreamingRpc\022\032.grpc.tes" +
      "ting.EarthRequest\032\033.grpc.testing.EarthRe" +
      "sponse\"\0000\001\022Q\n\020BidiStreamingRpc\022\032.grpc.te" +
      "sting.EarthRequest\032\033.grpc.testing.EarthR" +
      "esponse\"\000(\0010\001B2\n\033com.sample.grpc.protode" +
      "fineB\021EarthServiceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_testing_EarthRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_testing_EarthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_EarthRequest_descriptor,
        new java.lang.String[] { "RequestMessage", });
    internal_static_grpc_testing_EarthResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_testing_EarthResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_EarthResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
