// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MoonService.proto

package com.sample.grpc.protodefine;

public final class MoonServiceProto {
  private MoonServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MoonRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.testing.MoonRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    java.lang.String getRequestMessage();
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestMessageBytes();
  }
  /**
   * <pre>
   * A Moon request message type for test.
   * </pre>
   *
   * Protobuf type {@code grpc.testing.MoonRequest}
   */
  public  static final class MoonRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.testing.MoonRequest)
      MoonRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MoonRequest.newBuilder() to construct.
    private MoonRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoonRequest() {
      requestMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MoonRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MoonRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              requestMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.class, com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.Builder.class);
    }

    public static final int REQUESTMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestMessage_;
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    public java.lang.String getRequestMessage() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string requestMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRequestMessageBytes() {
      java.lang.Object ref = requestMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRequestMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRequestMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sample.grpc.protodefine.MoonServiceProto.MoonRequest)) {
        return super.equals(obj);
      }
      com.sample.grpc.protodefine.MoonServiceProto.MoonRequest other = (com.sample.grpc.protodefine.MoonServiceProto.MoonRequest) obj;

      if (!getRequestMessage()
          .equals(other.getRequestMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + REQUESTMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getRequestMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sample.grpc.protodefine.MoonServiceProto.MoonRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A Moon request message type for test.
     * </pre>
     *
     * Protobuf type {@code grpc.testing.MoonRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.testing.MoonRequest)
        com.sample.grpc.protodefine.MoonServiceProto.MoonRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.class, com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.Builder.class);
      }

      // Construct using com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonRequest_descriptor;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonRequest getDefaultInstanceForType() {
        return com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonRequest build() {
        com.sample.grpc.protodefine.MoonServiceProto.MoonRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonRequest buildPartial() {
        com.sample.grpc.protodefine.MoonServiceProto.MoonRequest result = new com.sample.grpc.protodefine.MoonServiceProto.MoonRequest(this);
        result.requestMessage_ = requestMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sample.grpc.protodefine.MoonServiceProto.MoonRequest) {
          return mergeFrom((com.sample.grpc.protodefine.MoonServiceProto.MoonRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sample.grpc.protodefine.MoonServiceProto.MoonRequest other) {
        if (other == com.sample.grpc.protodefine.MoonServiceProto.MoonRequest.getDefaultInstance()) return this;
        if (!other.getRequestMessage().isEmpty()) {
          requestMessage_ = other.requestMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sample.grpc.protodefine.MoonServiceProto.MoonRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sample.grpc.protodefine.MoonServiceProto.MoonRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object requestMessage_ = "";
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public java.lang.String getRequestMessage() {
        java.lang.Object ref = requestMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMessageBytes() {
        java.lang.Object ref = requestMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder setRequestMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder clearRequestMessage() {
        
        requestMessage_ = getDefaultInstance().getRequestMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string requestMessage = 1;</code>
       */
      public Builder setRequestMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.testing.MoonRequest)
    }

    // @@protoc_insertion_point(class_scope:grpc.testing.MoonRequest)
    private static final com.sample.grpc.protodefine.MoonServiceProto.MoonRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sample.grpc.protodefine.MoonServiceProto.MoonRequest();
    }

    public static com.sample.grpc.protodefine.MoonServiceProto.MoonRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoonRequest>
        PARSER = new com.google.protobuf.AbstractParser<MoonRequest>() {
      @java.lang.Override
      public MoonRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoonRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MoonRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoonRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sample.grpc.protodefine.MoonServiceProto.MoonRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MoonResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.testing.MoonResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    java.lang.String getResponseMessage();
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * <pre>
   * A Moon response message type for test.
   * </pre>
   *
   * Protobuf type {@code grpc.testing.MoonResponse}
   */
  public  static final class MoonResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:grpc.testing.MoonResponse)
      MoonResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MoonResponse.newBuilder() to construct.
    private MoonResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MoonResponse() {
      responseMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MoonResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MoonResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              responseMessage_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.class, com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.Builder.class);
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object responseMessage_;
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    public java.lang.String getResponseMessage() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        responseMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * An optional string message for test.
     * </pre>
     *
     * <code>string responseMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      java.lang.Object ref = responseMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResponseMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, responseMessage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResponseMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, responseMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sample.grpc.protodefine.MoonServiceProto.MoonResponse)) {
        return super.equals(obj);
      }
      com.sample.grpc.protodefine.MoonServiceProto.MoonResponse other = (com.sample.grpc.protodefine.MoonServiceProto.MoonResponse) obj;

      if (!getResponseMessage()
          .equals(other.getResponseMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSEMESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getResponseMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sample.grpc.protodefine.MoonServiceProto.MoonResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A Moon response message type for test.
     * </pre>
     *
     * Protobuf type {@code grpc.testing.MoonResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.testing.MoonResponse)
        com.sample.grpc.protodefine.MoonServiceProto.MoonResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.class, com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.Builder.class);
      }

      // Construct using com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        responseMessage_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sample.grpc.protodefine.MoonServiceProto.internal_static_grpc_testing_MoonResponse_descriptor;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonResponse getDefaultInstanceForType() {
        return com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonResponse build() {
        com.sample.grpc.protodefine.MoonServiceProto.MoonResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sample.grpc.protodefine.MoonServiceProto.MoonResponse buildPartial() {
        com.sample.grpc.protodefine.MoonServiceProto.MoonResponse result = new com.sample.grpc.protodefine.MoonServiceProto.MoonResponse(this);
        result.responseMessage_ = responseMessage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sample.grpc.protodefine.MoonServiceProto.MoonResponse) {
          return mergeFrom((com.sample.grpc.protodefine.MoonServiceProto.MoonResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sample.grpc.protodefine.MoonServiceProto.MoonResponse other) {
        if (other == com.sample.grpc.protodefine.MoonServiceProto.MoonResponse.getDefaultInstance()) return this;
        if (!other.getResponseMessage().isEmpty()) {
          responseMessage_ = other.responseMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sample.grpc.protodefine.MoonServiceProto.MoonResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sample.grpc.protodefine.MoonServiceProto.MoonResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object responseMessage_ = "";
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public java.lang.String getResponseMessage() {
        java.lang.Object ref = responseMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          responseMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        java.lang.Object ref = responseMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        responseMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder clearResponseMessage() {
        
        responseMessage_ = getDefaultInstance().getResponseMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * An optional string message for test.
       * </pre>
       *
       * <code>string responseMessage = 1;</code>
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        responseMessage_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:grpc.testing.MoonResponse)
    }

    // @@protoc_insertion_point(class_scope:grpc.testing.MoonResponse)
    private static final com.sample.grpc.protodefine.MoonServiceProto.MoonResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sample.grpc.protodefine.MoonServiceProto.MoonResponse();
    }

    public static com.sample.grpc.protodefine.MoonServiceProto.MoonResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MoonResponse>
        PARSER = new com.google.protobuf.AbstractParser<MoonResponse>() {
      @java.lang.Override
      public MoonResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MoonResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MoonResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MoonResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sample.grpc.protodefine.MoonServiceProto.MoonResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_MoonRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_MoonRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_testing_MoonResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_testing_MoonResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021MoonService.proto\022\014grpc.testing\"%\n\013Moo" +
      "nRequest\022\026\n\016requestMessage\030\001 \001(\t\"\'\n\014Moon" +
      "Response\022\027\n\017responseMessage\030\001 \001(\t2\305\002\n\013Mo" +
      "onService\022C\n\010UnaryRpc\022\031.grpc.testing.Moo" +
      "nRequest\032\032.grpc.testing.MoonResponse\"\000\022O" +
      "\n\022ClientStreamingRpc\022\031.grpc.testing.Moon" +
      "Request\032\032.grpc.testing.MoonResponse\"\000(\001\022" +
      "O\n\022ServerStreamingRpc\022\031.grpc.testing.Moo" +
      "nRequest\032\032.grpc.testing.MoonResponse\"\0000\001" +
      "\022O\n\020BidiStreamingRpc\022\031.grpc.testing.Moon" +
      "Request\032\032.grpc.testing.MoonResponse\"\000(\0010" +
      "\001B1\n\033com.sample.grpc.protodefineB\020MoonSe" +
      "rviceProtoP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_testing_MoonRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_testing_MoonRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_MoonRequest_descriptor,
        new java.lang.String[] { "RequestMessage", });
    internal_static_grpc_testing_MoonResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_testing_MoonResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_testing_MoonResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
